project:
  type: website
  output-dir: docs

website:
  title: "Nick Penzel"
  navbar:
    left:
    - href: index.qmd
      text: About
    - href: resources.qmd
      text: Projects
    - href: media/resume.pdf
      text: Resume
      
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

